name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-secondary-workflow:
    uses: "./.github/workflows/responder.yml"
    with:
      TEST: "Hello from Caller"

  process-response:
    needs: call-secondary-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print response from responder workflow
        run: echo "Response from secondary workflow ${{ needs.call-secondary-workflow.outputs.hello }}"
