name: Create release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  create-files:
    name: Create files
    uses: ./.github/workflows/main.yml
    with:
      # settings for the output file
      OUTPUT_NAME: 'update'
      OUTPUT_EXT: 'txt'
      OUTPUT_APPEND_VERSION: false
      OUTPUT_APPEND_BUILD_NUMBER: false

  release:
    name: Create a release
    needs: create-files
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Test
        run: ls

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" 'update.txt#Der aktuelle Stand' \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#1}" \
              --generate-notes
