name: Main workflow

on:
  workflow_call:
    inputs:
      OUTPUT_NAME:
        required: true
        type: string
      OUTPUT_EXT:
        required: false
        type: string
        default: 'txt'
      OUTPUT_APPEND_VERSION:
        required: false
        type: boolean
        default: false
      OUTPUT_APPEND_BUILD_NUMBER:
        required: false
        type: boolean
        default: false

env:
  FILENAME: ${{ inputs.OUTPUT_NAME }}

permissions:
  contents: write

jobs:
  update-of-file:
    name: Creation of the output file
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
#      - name: Update build file
#        run: echo ${{ github.run_number }} > BUILD

#      - name: Get build information from version file
#        run: |
#          BUI=$(cat BUILD)
#          echo "BUILD=$BUI" >> $GITHUB_ENV          
#          let "BUILD = BUILD+1"
#          echo "BUILD" >> $GITHUB_ENV

      - name: Read and increment build number
        id: increment
        run: |
          # Datei mit der Build-Nummer
          FILE="BUILD"

          # Sicherstellen, dass die Datei existiert
          if [ ! -f "$FILE" ]; then
            echo "0" > $FILE
          fi

          # Zahl auslesen, um 1 erhöhen und in die Datei schreiben
          BUILD_NUMBER=$(cat $FILE)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo $NEW_BUILD_NUMBER > $FILE

          # Neuen Wert als Ausgabe des Schrittes definieren
          echo "new_build_number=$NEW_BUILD_NUMBER" >> $GITHUB_ENV
          echo "::set-output name=new_build_number::$NEW_BUILD_NUMBER"

      # Here comes the magic of building :-)
      - name: Create output file
        run: |
          echo 'Test' > mynewfile
          date >> mynewfile

      - name: Test
        run: echo "Build ${{ env.BUILD }}"
        
      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: BUILD

      - name: Upload generated file
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: mynewfile

  commit-and-push:
    name: Commit and push output file
    needs: update-of-file
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download build file
        uses: actions/download-artifact@v4
        with:
          name: build-file

      - name: Download generated file
        uses: actions/download-artifact@v4
        with:
          name: output-file

      - name: Get version information from version file
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Append version information to file name, if requested
        if: ${{ inputs.OUTPUT_APPEND_VERSION }}
        run: echo "FILENAME=${{ env.FILENAME }}-${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Append build number to file name, if requested
        if: ${{ inputs.OUTPUT_APPEND_BUILD_NUMBER }}
        run: echo "FILENAME=${{ env.FILENAME }}-b${{ github.run_number }}" >> $GITHUB_ENV

      - name: Append file extension to file name
        run: echo "FILENAME=${{ env.FILENAME }}.${{ inputs.OUTPUT_EXT }}" >> $GITHUB_ENV

      - name: Rename output file before commit
        run: mv mynewfile $FILENAME

      - name: Commit and Push file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "sajde"
          git config --global user.email "116970472+sajde@users.noreply.github.com"
          git add BUILD
          git add $FILENAME
          git commit -m "updated files"
          git push
