name: Main workflow

on:
  workflow_call:
    inputs:
      OUTPUT_NAME:
        required: true
        type: string
      OUTPUT_EXT:
        required: false
        type: string
        default: 'txt'
      OUTPUT_APPEND_VERSION:
        required: false
        type: boolean
        default: false
      OUTPUT_APPEND_BUILD_NUMBER:
        required: false
        type: boolean
        default: false

env:
  FILENAME: ${{ inputs.OUTPUT_NAME }}

permissions:
  contents: write

jobs:
  update-of-date-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get version information from version file
        run: |
          VER=$(cat version.txt)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Append version information to file name
        if: ${{ inputs.OUTPUT_APPEND_VERSION }}
        run: echo "FILENAME=${{ env.FILENAME }}-${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Append build number to file name
        if: ${{ inputs.OUTPUT_APPEND_BUILD_NUMBER }}
        run: echo "FILENAME=${{ env.FILENAME }}-b${{ github.run_number }}" >> $GITHUB_ENV

      - name: Append file extension to file name
        run: echo "FILENAME=${{ env.FILENAME }}.${{ inputs.OUTPUT_EXT }}" >> $GITHUB_ENV

      - name: Test
        run: echo $FILENAME

      - name: Create update file
        run: |
          echo 'Test' > $FILENAME
          date >> $FILENAME

      - name: Commit and Push file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "sajde"
          git config --global user.email "116970472+sajde@users.noreply.github.com"
          git add $FILENAME
          git commit -m "updated file"
          git push
