on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

env:
  FILENAME: 'update.txt'
  LATESTNAME: 'latest.txt'

permissions:
  contents: write

jobs:
  update-of-date-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create update file
        run: |
          echo 'Test' > $FILENAME
          date >> $FILENAME

      - name: Commit and Push file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "sajde"
          git config --global user.email "116970472+sajde@users.noreply.github.com"
          git add $FILENAME
          git commit -m "updated file"
          git push
