name: Responder Workflow

on:
  workflow_call:
    inputs:
      TEST:
        description: "Input from caller workflow"
        required: true

outputs:
  HELLO:
    description: "Response based on the input TEST"

jobs:
  process-input:
    runs-on: ubuntu-latest
    steps:
      - name: Process input TEST
        id: process
        run: |
          if [ "${{ inputs.TEST }}" == "Hello from Caller" ]; then
            echo "HELLO=Hello back to Caller" >> $GITHUB_ENV
          else
            echo "HELLO=Unknown input" >> $GITHUB_ENV

      - name: Set output HELLO
        run: echo "HELLO=${{ env.HELLO }}"
        id: set-output
        env:
          HELLO: ${{ env.HELLO }}
        outputs:
          HELLO: ${{ env.HELLO }}
