name: Update test file

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-workflow:
    uses: ./.github/workflows/main.yml
    with:
      # setting for the output file
      OUTPUT_NAME: 'update'
      OUTPUT_EXT: 'txt'
      APPEND_VERSION: true
      APPEND_BUILD_NUMBER: true
