name: Update test file

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OUTPUTNAME: 'update.txt'

permissions:
  contents: write

jobs:
  main-workflow:
    uses: ./.github/workflows/main.yml
    with: 
      OUTPUTNAME: 'update.txt'
