name: Update test file

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-workflow:
    name: Main workflow
    uses: ./.github/workflows/main.yml
    with:
      # settings for the output file
      OUTPUT_NAME: 'update'
      OUTPUT_EXT: 'txt'
      OUTPUT_APPEND_VERSION: true
      OUTPUT_APPEND_BUILD_NUMBER: true

  check-name:
    needs: main-workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Print response from main workflow
        run: echo "Response from secondary workflow ${{ needs.main-workflow.outputs.outputfile }}"
