name: Update test file

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-of-date-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create update file
        run: |
          date > update.txt

      - name: Commit and Push file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "sajde"
          git config --global user.email "116970472+sajde@users.noreply.github.com"
          git add update.txt
          git commit -m "updated file"
          git push
