name: Update test file

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-workflow:
    name: Main workflow
    uses: ./.github/workflows/main.yml
    with:
      # settings for the output file
      OUTPUT_NAME: 'update'
      OUTPUT_EXT: 'txt'
      OUTPUT_APPEND_VERSION: false
      OUTPUT_APPEND_BUILD_NUMBER: false
