name: Update test file

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OUTPUTNAME: 'update.txt'

permissions:
  contents: write

jobs:
  main-workflow:
    uses: ./.github/workflows/main.yml
    with:
      # there's no easy way of using a variable for 'with', so it's hard-coded
      OUTPUTNAME: 'update.txt'
